packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.32.0
  prettier: ^3.6.2
  typescript: ^5.9.2
  react: ^19.1.1
  react-dom: ^19.1.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@types/node': ^24.1.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
