packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.20.0
  prettier: ^3.5.0
  typescript: ^5.7.3
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@types/node": ^22.13.1
