packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.9.1
  prettier: ^3.3.3
  typescript: ^5.5.4
  tailwindcss: ^3.4.10
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.5
  "@types/react-dom": ^18.3.0
  "@types/node": ^22.5.4
