packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.10.0
  prettier: ^3.3.3
  typescript: ^5.6.2
  tailwindcss: ^3.4.12
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.8
  "@types/react-dom": ^18.3.0
  "@types/node": ^22.5.5
