packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.17.0
  prettier: ^3.4.2
  typescript: ^5.7.2
  tailwindcss: ^3.4.16
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.2
  "@types/node": ^22.10.2
