packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.16.0
  prettier: ^3.4.2
  typescript: ^5.7.2
  tailwindcss: ^3.4.16
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@types/node": ^22.10.1
