packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.20.1
  prettier: ^3.5.1
  typescript: ^5.7.3
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@types/node": ^22.13.4
