packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.13.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  tailwindcss: ^3.4.14
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.11
  "@types/react-dom": ^18.3.1
  "@types/node": ^22.7.7
