packages:
  - tooling/*
  - examples/*

catalog:
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.4
  tailwindcss: ^3.4.7
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@types/node": ^20.14.12
